version: '3'
services:
  wordpress:
    # image: wordpress:5.2.2
    build: ./wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - 8088:80
      - 443:443

  mysql:
    image: mariadb:10.2.16
    container_name: mysql
    restart: always
    #command: "--default-authentication-plugin=mysql_native_password"
    env_file: .env
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql_job_backup/backup:/opt/mysql/backup
    #build: ./mysql_job_backup/restore

  mysql_jobs:
    build: ./mysql_job_backup
    container_name: mysql_backup
    user: root
    env_file: .env
    volumes:
      - ./mysql_job_backup/backup:/opt/mysql/backup
    command: crond -f -d 8
    restart: always


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 3333:8080
    env_file: .env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
        - '80:80'
    volumes:
        - ./logs/nginx/:/var/log/nginx
    build:
       context: .
    links:
        - wordpress
    restart: always

#wordpress http://wp-docker.test/wp-admin
#username: wp_docker
#password: wp_docker2019