version: '3'
services:
  wordpress:
    image: wordpress:5.2.2
    container_name: wordpress
    restart: always
    volumes:
      #- ./wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db #use db service to bind mysql
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
    ports:
      - 8088:80
      - 443:443

  db:
    image: mysql:8
    container_name: mysql
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wpdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
      
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 3333:8080
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORT: password

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
        - '80:80'
    volumes:
        - ./logs/nginx/:/var/log/nginx
    build:
       context: .
    links:
        - wordpress
    restart: always

#wordpress login
#username: wp_docker
#password: wp_docker2019