#!/bin/sh

echo "Start Mysql Backup Proccess"
BACKUP_FOLDER="/opt/mysql/backup/weekly"
NOW=$(date "+%Y-%m-%d-%H:%M:%S")

GZIP="$(which gzip)"
MYSQLDUMP="$(which mysqldump)"

### MySQL Server Login info ###
MDB=$MYSQL_DATABASE
MHOST=$MYSQL_CONTAINER_NAME
MPASS="$MYSQL_ROOT_PASSWORD"
MUSER="root"

[ ! -d "$BACKUP_FOLDER" ] && mkdir -p "$BACKUP_FOLDER"

FILE=$BACKUP_FOLDER/backup-weekly-$MDB-$NOW.sql.gz
$MYSQLDUMP -h $MHOST -u $MUSER -p$MPASS $MDB | $GZIP -9 > $FILE
echo 'Backup Database Successfuly on Weekly Shedule!'